### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by hb194812** [dr-costas/dnd-sed#3] opened 2020-11-22 12:43 UTC
Hi，I have obtained the TUT-SED Synthetic 2016 database, but I have encountered some problems in the feature extraction section. I would like to know the specific process of audio feature extraction. I would be very grateful if you could show me your code.

**Comment by dr-costas** [comment] 2020-12-01 15:03
Hi, sorry for the delay. 

You can find the features at the website of the dataset. There is a link for direct download of the features. 

If there is some specific problem that you encounter, then please feel free to ask.

**Comment by hb194812** [comment] 2020-12-03 08:37
Thank you for your reply. I have already downloaded the features. You have mentioned that the features and the target values should be saved as separate files. How does this process work here? How do you match the feature file to the target value file? This is my email address: 2278763464@qq.com. I just want to briefly repeat the experiment. If possible, could you please send me the files that having the input values and the target values? Thank you so much!

**Comment by dr-costas** [comment] 2020-12-03 08:40
The features and labels are `numpy` arrays, as far as I remember. Splitting those is simple, using existing `numpy` functionalities. The experiment can be reproduced fairly easy with the existing code at the repository and the online available features from the TUTSED Synthetic dataset. 

Every sequence of input features, has a corresponding sequence of labels. You just have to load the numpy array that has the features and the labels, and then create to separate arrays. Then, split these arrays and save them with names that you want, and change the corresponding fields in the code so the code will be able to load them.

**Comment by dr-costas** [comment] 2020-12-03 08:43
If there is not a problem in the code, I will close this issue since it is not referred to the code. Please feel free to create another issue if you encounter any problems with the code.

**Closed as completed by dr-costas** 2020-12-03 08:43 UTC
